"""notifications v2

Revision ID: 3952db7075cf
Revises: 0c9fa1000df5
Create Date: 2020-05-15 14:47:45.117993

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3952db7075cf'
down_revision = '0c9fa1000df5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_message_read_time')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('last_message_read_time', sa.DATETIME(), nullable=True))
    # ### end Alembic commands ###
